version: '3.2'

services:
  agent:
    image: portainer/agent:develop
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9002
      LOG_LEVEL: DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 9002
        published: 9002
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global

networks:
  portainer_agent:
    driver: overlay
